default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
#  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'db' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>

development:
  <<: *default
  database: ecovpp_development

test:
  <<: *default
  database: ecovpp_test

production:
  <<: *default
  database: ecovpp_development
